#!/usr/bin/env python

import sys
from electrum import Network
from electrum.util import json_encode, print_msg

try:
    i = int(sys.argv[1])
except Exception:
    sys.exit(1)

n = Network()
n.start()
h = n.synchronous_get(('blockchain.block.get_chunk',[i]))
print_msg(json_encode(h))
